$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: customer_purchase_ml_environment
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ../../../data-science/environment/train-conda.yml
description: Environment created from a Docker image with a Conda configuration for customer purchase prediction.
